apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  # Point to this repository for self-management
  repositories: |
    - url: https://github.com/piyanshu-mindstix/argocd-poc
  # Other config settings...